### ISSUE TITLE
[orion] Replica Set only set with multihosts

### ISSUE THREAD

**Issue by sromerotech** [FIWARE/helm-charts#74]
I'm deploying mongodb in ReplicaSet mode with a headless service, so my mongodb host is `mongodb-headless`. I can't set de RS value because of [this](https://github.com/FIWARE/helm-charts/blob/main/charts/orion/templates/deployment.yaml#L196) restriction. It would be great to set RS independently to the number of hosts.

**Comment by wistefan** [comment]
Hello @sergiorb ,
I will take a look into it. If I remember correctly, this restriction was set due to orion having problems discovering the instances below the headless service. Therefor we call them via <POD_NAME>.mongodb-headless and list all of them there. But I will check if thats still the case.

**Comment by sbanoeon** [comment]
Hello @wistefan, can you please elaborate what does it mean that orion is having problems discovering the instances below headless service. I am also using headless service in front of orion, and somehow there is a problem in accessing primary node for write requests through the headless service.
